name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v5

            - name: Setup do Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13' 

            - name: Instalação das Dependencias 
              working-directory: ./src
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            - name: Execução dos testes
              working-directory: ./src
              run: |
                python -m pytest tests/ -v                 

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with: 
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: ./src
                file: ./src/Dockerfile
                push: true
                tags: |
                  wili4m/encontros-tech:latest
                  wili4m/encontros-tech:v${{ github.run_number }}                 

    CD-Homolog:
        runs-on: ubuntu-latest
        needs: [CI]
        environment: homologacao
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v5

            - name: Configurar contexto Kubernetes
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBE_CONFIG }}

            - name: Criar namespace de homologação
              run: kubectl create namespace tech-homolog --dry-run=client -o yaml | kubectl apply -f -

            - name: Create secrets in prod
              run: |
                kubectl create secret generic database-secret \
                  --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                  --namespace=tech-homolog \
                  --dry-run=client -o yaml | kubectl apply -f -

            - name: Deploy no ambiente de homologação
              uses: azure/k8s-deploy@v5
              with:
                namespace: 'tech-homolog'
                manifests: |
                  k8s/deployment.yaml

    CD-Prod:
        runs-on: ubuntu-latest
        needs: [CD-Homolog]
        environment: producao
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v5

            - name: Configurar contexto Kubernetes
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBE_CONFIG }}

            - name: Criar namespace de produção
              run: kubectl create namespace tech-prod --dry-run=client -o yaml | kubectl apply -f -

            - name: Create secrets in prod
              run: |
                kubectl create secret generic database-secret \
                  --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                  --namespace=tech-prod \
                  --dry-run=client -o yaml | kubectl apply -f -

            - name: Deploy no ambiente de produção
              uses: azure/k8s-deploy@v5
              with:
                namespace: 'tech-prod'
                manifests: |
                  k8s/deployment.yaml