# Nome da Automação:
name: CI-CD

# Action:
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Conjuntos de execuções executadas em uma determinada ordem
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # aqui poderia ser utilizados os comandos.
      # ex: 
      # git clone ...
      # git checkout ...
      # Mas o Actions já faz isso automaticamente com Marketplace. 
      - name: Obtendo o código do projeto
        uses: actions/checkout@v5.0.0

      - name: Setup do Python
        uses: actions/setup-python@v6

      - name: Instalação das Dependencias
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execução dos Testes
        working-directory: ./src
        run: |
          python -m pytest tests/ -v

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            wili4m/encontros-tech-labs:latest
            wili4m/encontros-tech-labs:v${{ github.run_number }}
  
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - run: echo "Obter o código"
      - run: echo "Configurar o Kubeconfig"
      - run: echo "Executar o apply"
