# Nome da Automação:
name: CI-CD

# Action:
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Conjuntos de execuções executadas em uma determinada ordem
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter o código"
      - run: echo "Executar o Docker Build"
      - run: echo "Enviar a Imagem Docker para o Docker Hub"
  
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter o código"
      - run: echo "Configurar o Kubeconfig"
      - run: echo "Executar o apply"
