name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v5

            - name: Setup do Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13' 

            - name: Instalação das Dependencias 
              working-directory: ./src
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            - name: Execução dos testes
              working-directory: ./src
              run: |
                python -m pytest tests/ -v                 

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with: 
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: ./src
                file: ./src/Dockerfile
                push: true
                tags: |
                  wili4m/encontros-tech:latest
                  wili4m/encontros-tech:v${{ github.run_number }}                 

    CD:
        runs-on: ubuntu-latest
        needs: [CI]
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v5

            - name: Configurar contexto Kubernetes
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBE_CONFIG }}

            - name: Deploy no cluster Kubernetes
              uses: azure/k8s-deploy@v5
              with:
                manifests: |
                  k8s/deployment.yaml